# Generated by Django 4.2.16 on 2025-02-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'Данные об оплате', 'verbose_name_plural': 'Данные об оплатах'},
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transaction',
        ),
    ]
