# Generated by Django 5.0.1 on 2024-11-01 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_products_similar_products'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageTextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageContentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_above', models.CharField(blank=True, max_length=150, verbose_name='Надпись сверху')),
                ('image1', models.ImageField(upload_to='main_page_images', verbose_name='Большое фото 1')),
                ('alignment', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='left', max_length=5, verbose_name='Расположение')),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='goods.products', verbose_name='Продукт 1')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='goods.products', verbose_name='Продукт 2')),
            ],
        ),
    ]
