# Generated by Django 4.2.16 on 2024-11-19 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mainpageimage_content_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название карусели')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousels/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото карусели',
                'verbose_name_plural': 'Фото каруселей',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='MainPageImage',
        ),
        migrations.AddField(
            model_name='carousel',
            name='images',
            field=models.ManyToManyField(related_name='carousels', to='main.carouselimage', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='mainpagecontentbox',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_boxes', to='main.carousel', verbose_name='Карусель'),
        ),
    ]
