# Generated by Django 5.0.1 on 2024-11-01 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mainpagecontentbox_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Главная страница', max_length=200)),
            ],
            options={
                'verbose_name': 'Главная страница',
                'db_table': 'main_page',
            },
        ),
        migrations.AlterModelOptions(
            name='mainpagecontentbox',
            options={'ordering': ['order'], 'verbose_name': 'Блок контента', 'verbose_name_plural': 'Блоки контента'},
        ),
        migrations.AlterModelOptions(
            name='mainpagetextbox',
            options={'ordering': ['order'], 'verbose_name': 'Блок текста', 'verbose_name_plural': 'Блоки текста'},
        ),
        migrations.AddField(
            model_name='mainpagecontentbox',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainpagetextbox',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainpagecontentbox',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_boxes', to='main.mainpage'),
        ),
        migrations.AddField(
            model_name='mainpagetextbox',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_boxes', to='main.mainpage'),
        ),
    ]
