# Generated by Django 4.2.16 on 2024-11-19 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carousel_carouselimage_delete_mainpageimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='caroisel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='main.carousel', verbose_name='Карусель'),
        ),
    ]
