# Generated by Django 4.2.16 on 2024-11-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_carouselimage_caroisel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусели'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='order',
        ),
    ]
