# Generated by Django 4.2.16 on 2024-11-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_carousel_options_remove_carousel_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagecontentbox',
            name='image1',
        ),
    ]
