# Generated by Django 4.2.16 on 2025-01-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_mainpagecontentbox_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=models.TextField(verbose_name='Контент страницы'),
        ),
    ]
