# Generated by Django 4.2.16 on 2025-01-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_infopage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная страница'),
        ),
    ]
