# Generated by Django 4.2.16 on 2025-01-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainpage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagetextbox',
            name='title',
            field=models.TextField(blank=True, verbose_name='Заголовок'),
        ),
    ]
