# Generated by Django 4.2.16 on 2025-01-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_mainpagetextbox_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontentbox',
            name='title',
            field=models.TextField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
