# Generated by Django 4.2.16 on 2025-01-26 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mainpagecontentbox_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='main.mainpage'),
        ),
    ]
