# Generated by Django 4.2.16 on 2025-01-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_carousel_main_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='main_page',
        ),
        migrations.CreateModel(
            name='CarouselBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='main.carousel', verbose_name='Карусель')),
                ('main_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_boxes', to='main.mainpage')),
            ],
            options={
                'verbose_name': 'Блок-карусель',
                'verbose_name_plural': 'Блок-карусели',
                'db_table': 'main_page_carousel_box',
            },
        ),
    ]
