# Generated by Django 4.2.16 on 2025-01-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_carouselblock_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='caroisel',
            new_name='carousel',
        ),
        migrations.RenameField(
            model_name='mainpagecontentbox',
            old_name='images',
            new_name='carousel',
        ),
    ]
