# Generated by Django 4.2.16 on 2025-01-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_caroisel_carouselimage_carousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название карусели'),
        ),
        migrations.AlterField(
            model_name='mainpagecontentbox',
            name='title',
            field=models.TextField(blank=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpagetextbox',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
