# Generated by Django 4.2.16 on 2025-02-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=models.TextField(verbose_name='Контент страницы'),
        ),
    ]
