# Generated by Django 4.2.16 on 2025-10-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_infopage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselblock',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='carouselblock',
            name='main_page',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='carousel',
        ),
        migrations.DeleteModel(
            name='InfoPage',
        ),
        migrations.RemoveField(
            model_name='mainpagecontentbox',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='mainpagecontentbox',
            name='main_page',
        ),
        migrations.RemoveField(
            model_name='mainpagecontentbox',
            name='product1',
        ),
        migrations.RemoveField(
            model_name='mainpagecontentbox',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='mainpagetextbox',
            name='main_page',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='CarouselBlock',
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
        migrations.DeleteModel(
            name='MainPageContentBox',
        ),
        migrations.DeleteModel(
            name='MainPageTextBox',
        ),
    ]
