# Generated by Django 4.2.16 on 2025-12-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_carouselblock_carousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='telegram',
            field=models.CharField(max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон Whatsapp'),
        ),
    ]
