# Generated by Django 4.2.16 on 2026-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contactinfo_telegram_alter_contactinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='vk',
            field=models.CharField(max_length=50, null=True, verbose_name='ВКонтакте'),
        ),
    ]
