# Generated by Django 4.2.16 on 2026-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactinfo_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон Whatsapp'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ВКонтакте'),
        ),
    ]
