# Generated by Django 4.2.16 on 2024-11-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='LaundryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Способ стирки')),
                ('icon', models.ImageField(upload_to='laundry_icons')),
            ],
            options={
                'verbose_name': 'Способ стирки',
                'verbose_name_plural': 'Способы стирки',
                'db_table': 'laundry_features',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('compound', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('discount_price', models.PositiveBigIntegerField(default=0, verbose_name='Цена по скидке')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория')),
                ('laundry_features', models.ManyToManyField(blank=True, to='goods.laundryfeature')),
                ('similar_products', models.ManyToManyField(blank=True, related_name='similar_to_this', to='goods.products', verbose_name='Похожие товары')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods_images', verbose_name='Фото')),
                ('layout', models.CharField(blank=True, choices=[('large', 'Большая'), ('small', 'Маленькая')], max_length=10, null=True, verbose_name='Размер')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продуктов',
                'db_table': 'product_image',
                'ordering': ['order'],
            },
        ),
    ]
