# Generated by Django 4.2.16 on 2024-12-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='options',
            field=models.ManyToManyField(blank=True, to='goods.products', verbose_name='Товары-варианты'),
        ),
    ]
