# Generated by Django 5.0.1 on 2024-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_products_discount_products_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Способ стирки')),
                ('icon', models.ImageField(upload_to='laundry_icons')),
            ],
            options={
                'verbose_name': 'Способ стирки',
                'verbose_name_plural': 'Способы стирки',
                'db_table': 'laundry_features',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='compound',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='products',
            name='laundry_features',
            field=models.ManyToManyField(blank=True, to='goods.laundryfeature'),
        ),
    ]
