# Generated by Django 4.2.16 on 2025-10-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание коллекции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная коллекция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'db_table': 'collection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='goods.collections', verbose_name='Коллекции'),
        ),
    ]
