# Generated by Django 4.2.16 on 2025-10-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_collections_products_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='options',
        ),
    ]
