# Generated by Django 4.2.16 on 2025-10-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('group', models.CharField(choices=[('compound-flag', 'Флаг состава'), ('product-flag', 'Флаг товара')], max_length=150, verbose_name='Группа')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Флаг продукта',
                'verbose_name_plural': 'Флаги продукта',
                'db_table': 'flags',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='flags',
            field=models.ManyToManyField(blank=True, to='goods.flags', verbose_name='Флаги'),
        ),
    ]
