# Generated by Django 5.0.1 on 2024-11-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_products_similar_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods_images')),
                ('type', models.CharField(choices=[('main', 'Main (square images for hover effect)'), ('detail', 'Detail (product page images)')], max_length=10)),
                ('layout', models.CharField(blank=True, choices=[('large', 'Large (col-lg-12)'), ('small', 'Small (col-lg-6)')], max_length=10, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продуктов',
                'db_table': 'product image',
                'ordering': ['order'],
            },
        ),
    ]
