# Generated by Django 4.2.16 on 2025-11-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_flags_products_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='layout',
        ),
    ]
