# Generated by Django 5.0.1 on 2024-11-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_products_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.products'),
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
