# Generated by Django 4.2.16 on 2025-12-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_productimage_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='flags',
        ),
        migrations.AddField(
            model_name='products',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.flags', verbose_name='Флаг'),
        ),
    ]
