# Generated by Django 4.2.16 on 2025-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_products_flags_products_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XS', 'XS - Extra Small'), ('S', 'S - Small'), ('M', 'M - Medium'), ('L', 'L - Large'), ('XL', 'XL - Extra Large')], max_length=10, unique=True, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'db_table': 'sizes',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='goods.sizes', verbose_name='Размеры'),
        ),
    ]
