# Generated by Django 4.2.16 on 2025-12-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_sizes_products_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_images', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.collections', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Фото коллекции',
                'verbose_name_plural': 'Фото коллекции',
                'db_table': 'collection_image',
                'ordering': ['order'],
            },
        ),
    ]
