# Generated by Django 4.2.16 on 2026-03-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_collectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Цена по скидке'),
        ),
    ]
