# Generated by Django 4.2.16 on 2025-10-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название службы')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Базовая стоимость доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Служба доставки',
                'verbose_name_plural': 'Службы доставки',
                'db_table': 'delivery_service',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='—', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.deliveryservice', verbose_name='Служба доставки'),
        ),
    ]
