# Generated by Django 4.2.16 on 2025-12-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliveryservice_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
